### ISSUE TITLE
Protocol String.Chars not implemented for %Ecto.Schema.Metadata

### ISSUE THREAD

**Issue by ACPK** [Gazler/ecto_admin#3]
@Gazler Any clue why I get the following error when I visit http://localhost:4000/admin/users

```
protocol String.Chars not implemented for %Ecto.Schema.Metadata{source: "users", state: :loaded}
```

Here is the stacktrace:

```
[info] GET /admin/users
[debug] SELECT u0."id", u0."email", u0."hashed_password", u0."hashed_confirmation_token", u0."confirmed_at", u0."hashed_password_reset_token", u0."unconfirmed_email", u0."authentication_tokens", u0."inserted_at", u0."updated_at" FROM "users" AS u0 [] (4.8ms)
[info] Sent 500 in 61ms
[error] #PID<0.302.0> running PhoenixTokenAuthReact.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /admin/users
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %Ecto.Schema.Metadata{source: "users", state: :loaded}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        (ecto_admin) lib/ecto_admin/templates/index.eex:7: anonymous fn/3 in EctoAdmin.Resource.index/1
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto_admin) lib/ecto_admin/templates/index.eex:9: anonymous fn/3 in EctoAdmin.Resource.index/1
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ecto_admin) lib/ecto_admin/templates/index.eex:7: EctoAdmin.Resource.index/1
        (ecto_admin) lib/ecto_admin/router.ex:27: EctoAdmin.Router.handle_request/3
```

**Comment by tispratik** [comment]
+1

**Comment by Gazler** [comment]
https://github.com/smpallen99/ex_admin is probably what you want. This repo
is not in active development
